import type { Metadata, Viewport } from "next";
import "./globals.css";
import { TopNav } from "@/components/nav/TopNav";
import { MobileHeader } from "@/components/nav/MobileHeader";
import { BottomNav } from "@/components/nav/BottomNav";
import { ErrorBoundary } from "@/components/ui/ErrorBoundary";
import { ServiceWorkerRegister } from "@/components/ServiceWorkerRegister";

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000";

const defaultDescription =
  "DiveFinder is an independent, explainable dive destination recommendation engine — not a booking marketplace.";

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: "DiveFinder — Where should you dive next?",
    template: "%s · DiveFinder",
  },
  description: defaultDescription,
  // Site-wide fallback so any page shares with a real preview card instead
  // of a bare link — pages with their own real photo (destination, site,
  // species) override this via buildPageMetadata() in src/lib/utils/metadata.ts.
  openGraph: {
    title: { default: "DiveFinder — Where should you dive next?", template: "%s · DiveFinder" },
    description: defaultDescription,
    siteName: "DiveFinder",
    type: "website",
  },
  twitter: {
    card: "summary",
    title: { default: "DiveFinder — Where should you dive next?", template: "%s · DiveFinder" },
    description: defaultDescription,
  },
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "DiveFinder",
  },
  // Favicon is auto-generated by Next.js from src/app/icon.png. Apple
  // touch icon (home-screen shortcut on iPhone/iPad) is set explicitly
  // since iOS needs the 180x180 size specifically.
  icons: {
    apple: "/icons/apple-touch-icon.png",
  },
};

export const viewport: Viewport = {
  themeColor: "#0e1725",
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <TopNav />
        <MobileHeader />
        <div className="pb-20 md:pb-0" style={{ paddingBottom: "calc(5rem + var(--safe-area-bottom))" }}>
          <ErrorBoundary>{children}</ErrorBoundary>
        </div>
        <BottomNav />
        <ServiceWorkerRegister />
      </body>
    </html>
  );
}
